# -*- coding: utf-8 -*-
"""SSCD Ex 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j2nX7kMKjlUrtCJoNU5r8LDQLVWWjESq
"""

import re

j = 1
myfinlist = []
inp = re.split("([+-/*])",input("Enter Expression: "))
# inp = re.split("([+-/*])","a+b-c*d+e/d")
for i in inp:
    if i in ['*','/']:
      tmp = inp.index(i)
      ope = inp[tmp-1:tmp+2]
      myfinlist.append(''.join(inp[tmp-1:tmp+2]))
      tlist = inp[:tmp-1]+list(['t{}'.format(j)]) +inp[tmp+2:]
      inp = tlist
      j+=1

for i in inp:
    if i in ['+','-']:
        myfinlist.append(''.join(inp[:3]))
        inp = inp[2:]
        inp[0] = 't' + str(j)
        j+=1
n = 1
print("Three Address : ")
for i in myfinlist:
  print('t{}'.format(n),'=',i)
  n+=1

